### ISSUE TITLE
Example code for using with images

### ISSUE THREAD

**Issue by deebuls** [dsteinberg/libcluster#7]
This is wonderful library looking at the speed and the quality. Thanks for the wonderful library.

I would like to use it in out problem to detect tabletop objects. Please can you provide a sample code for using with images or some basic steps on how to use 

Thanks

**Comment by dsteinberg** [comment]
Thanks for the compliments!

This library just provides hierarchical Bayesian clustering algorithms, so using it with images is beyond the scope of just this repository. You'll first have to extract image features that can then be used by this library for clustering. Have a look at this paper http://dsteinberg.github.io/docs/CVIU_scene.pdf for how I did this in the past (some image features here https://github.com/dsteinberg/imdescrip). Also it's worth having a look at http://opencv.org/ and if using python, scikit-image and scikit-learn.

Good luck!
